# Generated by Django 5.0.1 on 2024-01-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English'), ('de', 'German')], max_length=2)),
                ('text', models.CharField(max_length=255)),
                ('answer_a', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_b', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_c', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=10)),
                ('media', models.CharField(blank=True, max_length=128, null=True)),
                ('question_source', models.TextField(blank=True, null=True)),
                ('security_explenation', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='questions', to='api.category')),
            ],
        ),
    ]
