# Generated by Django 5.0.1 on 2024-02-01 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_questioncomment_questioncommentanswer_like_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='api.questioncommentanswer'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='api.questioncomment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.questioncommentanswer'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.questioncomment'),
        ),
    ]
