# Generated by Django 5.0.1 on 2024-02-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dislike_answer_alter_dislike_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='QuestionCommentAnswer',
            new_name='CommentAnswer',
        ),
    ]
